# configure logos location and files
# centerLogo = false
# logo = "logos/logo.png"
footerLogo = "icons/copy.svg"

description = "Senior IT Consultant | OpenShift"
fallBackOgImage = "logos/logo.png"

mobileNavigation = "right"

# description on sidebar
introDescription = "System Engineer @ [SVA System Vertrieb Alexander GmbH](https://www.sva.de)"
since = "2025 "

# enable global search in sidebar
enableSearch = true

# set code number default
codeLineNumbers = false

# configure giscus plugin for github discussions
giscus = true
giscusRepo = "AndreiGavriliu/gavriliu.com"
giscusRepoId = "R_kgDOOJJrSA"
giscusCategory = "General"
giscusCategoryId = "DIC_kwDOOJJrSM4ComRe"
giscusMapping = "og:title"
giscusReactionsEnabled = "1"
giscusTheme = "light"
giscusLang = "en"

# configure umami analytics
# umami_data_website_id = "cf2e457b-8928-4ded-add0-4418eada5c79"
umami_data_website_id = "9927fd87-d2c6-4fe1-85b8-e07aea9e79d6"
umami_script_url = "https://umami.gavriliu.com/script.js"

[author]
name = "Andrei Gavriliu"

# [params]
#   [params.services]
#     [params.services.umami_analytics]
#     id = "cf2e457b-8928-4ded-add0-4418eada5c79"
#     script_url = "https://umami.gavriliu.com/script.js"
